trigger:
  - master

pool:
  name: 'AWS-ECS'
  # vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
    - repository: immunisation-fhir-api
      type: github
      name: NHSDigital/immunisation-fhir-api
      endpoint: nhsdigital   

steps:
- template: azure/components/aws-assume-role.yml@common
  parameters:
      role: "auto-ops"
      profile: "apm_ptl"

- template: "azure/components/get-aws-secrets-and-ssm-params.yml@common"
  parameters:
    secret_file_ids:
      - ptl/app-credentials/jwt_testing/non-prod/JWT_TESTING_PRIVATE_KEY
    secret_ids:
      - ptl/app-credentials/immunisation-fhir-api-testing-app/non-prod/INTROSPECTION_CLIENT_ID
      - ptl/app-credentials/immunisation-fhir-api-testing-app/non-prod/INTROSPECTION_CLIENT_SECRET
      - ptl/app-credentials/immunisation-fhir-api-testing-app/non-prod/INTROSPECTION_CLIENT_ID_INT
      - ptl/app-credentials/immunisation-fhir-api-testing-app/non-prod/INTROSPECTION_CLIENT_SECRET_INT
      - ptl/app-credentials/immunisation-fhir-api-testing-app/non-prod/INT_CLIENT_ID
      - ptl/app-credentials/immunisation-fhir-api-testing-app/non-prod/INT_CLIENT_SECRET

- template: azure/templates/aws-assume-role.yml@immunisation-fhir-api
  parameters:
      role: "auto-ops"
      profile: "apim-dev"
      aws_account: dev

- script: |
    echo "DEBUG: AWS Credentials"
    echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
    echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
    echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN"
    aws sts get-caller-identity || echo "AWS CLI failed"
  displayName: "DEBUG: Show AWS Credentials"

- script: |
    pyenv install -s 3.11.11
    pyenv local 3.11.11

    python3.11 --version
  displayName: 'Install Python 3.11'

- script: |
    echo "🔍 Checking Python version..."
    which python
    python --version
    which python3
    python3 --version
  displayName: 'Check Python Version'
  
- task: Bash@3
  displayName: 'Install dependencies'
  inputs:
    targetType: 'inline'
    script: |
      echo "Creating virtual environment"
      python -m venv venv
      source venv/bin/activate

      echo "Upgrading pip"
      python -m pip install --upgrade pip
      
      echo "Installing requirements"
      pip install -r requirements.txt
      pip install allure-pytest
  continueOnError: false       
  failOnStderr: true           

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "🔍 Activating virtualenv"
      source venv/bin/activate
      
      echo "🚀 Running Pytest-BDD tests"
      pytest --junitxml=output/test-results.xml
  continueOnError: true    
  failOnStderr: true        
  displayName: 'Run Pytest-BDD tests with Allure'
  env:
    auth_url: https://int.api.service.nhs.uk/oauth2-mock/authorize
    token_url: https://int.api.service.nhs.uk/oauth2-mock/token
    callback_url: https://oauth.pstmn.io/v1/callback
    Postman_Auth_client_Id: mNnjGa3dtSh7eKkMxkGjy3JXrAkvZW1s
    Postman_Auth_client_Secret: 2np7WP9Iz6NOKXMN
    username: aal3
    scope: nhs-cis2
    RAVS_client_Id: mKAFdGHvfAmRJIYCmrgvVAOms5X3gZiG
    RAVS_client_Secret: 8udIRfKfnFHZje3r
    MAVIS_client_Id: ZMFe92RMTQ7JntxAeOSe4ZlLmdlkBtnK
    MAVIS_client_Secret: IA9jmEHI04wKwH6C
    OPTUM_client_Id: hWAOPTqJLC2hjMEIC6Y5AiXyBBctSzrl
    OPTUM_client_Secret: FZIOoP8C9F8ng9Ht
    SONAR_client_Id: ooAGdMkVxkGDk3ioxT6nvmtopILi9A3u
    SONAR_client_Secret: bAgm21lNWITrFftY
    baseUrl: https://int.api.service.nhs.uk/immunisation-fhir-api/FHIR/R4
    aws_token_refresh: 'False'
    
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/output/test-results.xml'
    testRunTitle: 'BDD Test Summary'