trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install allure-pytest
  displayName: 'Install dependencies'

- script: |
    sudo apt update
    sudo apt install -y default-jre wget unzip
    wget https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.zip
    unzip allure-2.21.0.zip -d /opt/
    sudo ln -s /opt/allure-2.21.0/bin/allure /usr/bin/allure
    allure --version
  displayName: 'Install Allure CLI'

- script: |
    source venv/bin/activate
    pytest --alluredir=output/allure-results || true
  displayName: 'Run Pytest-BDD tests with Allure'

- task: Bash@3
  displayName: 'Generate Allure Report'
  inputs:
    targetType: 'inline'
    script: |
      allure generate output/allure-results --clean -o output/allure-report

- script: ls -la output/allure-report
  displayName: 'List Allure Report Contents'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Allure Report Artifact'
  inputs:
    pathToPublish: 'output/allure-report'
    artifactName: 'AllureReport'
    publishLocation: 'Pipeline'