trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

steps:
- template: azure/templates/aws-assume-role.yml@common
  parameters:
    role: auto-ops
    profile: apim-dev
    aws_account: dev

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
  
- script: |
    python -m venv venv
    source venv/bin/activate
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install allure-pytest
  displayName: 'Install dependencies'

- script: |
    sudo apt update
    sudo apt install -y default-jre wget unzip
    wget https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.zip
    unzip allure-2.21.0.zip -d /opt/
    sudo ln -s /opt/allure-2.21.0/bin/allure /usr/bin/allure
    allure --version
  displayName: 'Install Allure CLI'


- script: |
    source venv/bin/activate
    pytest --junitxml=output/test-results.xml || true
  displayName: 'Run Pytest-BDD tests with Allure'
  env:
    auth_url : https://int.api.service.nhs.uk/oauth2-mock/authorize
    token_url : https://int.api.service.nhs.uk/oauth2-mock/token
    callback_url : https://oauth.pstmn.io/v1/callback
    Postman_Auth_client_Id : mNnjGa3dtSh7eKkMxkGjy3JXrAkvZW1s
    Postman_Auth_client_Secret : 2np7WP9Iz6NOKXMN
    username : aal3
    scope : nhs-cis2

    RAVS_client_Id : mKAFdGHvfAmRJIYCmrgvVAOms5X3gZiG
    RAVS_client_Secret : 8udIRfKfnFHZje3r

    MAVIS_client_Id : ZMFe92RMTQ7JntxAeOSe4ZlLmdlkBtnK
    MAVIS_client_Secret : IA9jmEHI04wKwH6C

    OPTUM_client_Id : hWAOPTqJLC2hjMEIC6Y5AiXyBBctSzrl
    OPTUM_client_Secret : FZIOoP8C9F8ng9Ht

    SONAR_client_Id : ooAGdMkVxkGDk3ioxT6nvmtopILi9A3u
    SONAR_client_Secret : bAgm21lNWITrFftY

    baseUrl : https://int.api.service.nhs.uk/immunisation-fhir-api/FHIR/R4
    aws_token_refresh: 'False'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/output/test-results.xml'
    testRunTitle: 'BDD Test Summary'