class ScenarioContext:
    def __init__(self):
        self.soft_assertions = None
        self.token = None
        self.token_expires_in = None
        self.token_gen_time = None
        self.patient_id = None
        self.vaccine_type = None
        self.patient = None
        self.immunization_object = None
        self.url = None
        self.headers = None
        self.corrID = None
        self.reqID = None
        self.json_request = None
        self.response = None
        self.response_json = None
        self.auth_url = None
        self.token_url = None
        self.callback_url = None
        self.auth_client_Id= None
        self.auth_client_Secret = None
        self.username = None
        self.scope = None
        self.ImmsID = None
        self.request = None
        self.baseUrl = None
        self.location = None
        self.parsed_search__object= None
        self.created_event = None
        self.create_object = None
        self.Patient_fullUrl = None
